import { NextResponse } from "next/server";
import { getRegistrationPool } from "@/lib/postgres";

export const runtime = "nodejs";

type RegistrationPayload = {
  fullName?: unknown;
  email?: unknown;
  skinType?: unknown;
  category?: unknown;
  concerns?: unknown;
  selectedProductIds?: unknown;
};

function asCleanString(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

function asStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((item) => (typeof item === "string" ? item.trim() : ""))
    .filter(Boolean);
}

export async function POST(request: Request) {
  let payload: RegistrationPayload;
  try {
    payload = (await request.json()) as RegistrationPayload;
  } catch {
    return NextResponse.json({ error: "Invalid JSON payload." }, { status: 400 });
  }

  const fullName = asCleanString(payload.fullName);
  const email = asCleanString(payload.email);
  const skinType = asCleanString(payload.skinType) || null;
  const category = asCleanString(payload.category) || null;
  const concerns = asStringArray(payload.concerns);
  const selectedProductIds = asStringArray(payload.selectedProductIds);

  if (!fullName || !email) {
    return NextResponse.json(
      { error: "Full name and email are required." },
      { status: 400 },
    );
  }

  const pool = getRegistrationPool();

  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS registration_submissions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        full_name TEXT NOT NULL,
        email TEXT NOT NULL,
        skin_type TEXT,
        preferred_category TEXT,
        concerns TEXT[] NOT NULL DEFAULT '{}',
        selected_product_ids TEXT[] NOT NULL DEFAULT '{}',
        submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);

    await pool.query(`
      CREATE INDEX IF NOT EXISTS idx_registration_submissions_email
      ON registration_submissions(email);
    `);

    const insertResult = await pool.query(
      `
      INSERT INTO registration_submissions (
        full_name,
        email,
        skin_type,
        preferred_category,
        concerns,
        selected_product_ids
      )
      VALUES ($1, $2, $3, $4, $5, $6)
      RETURNING id, submitted_at;
      `,
      [fullName, email, skinType, category, concerns, selectedProductIds],
    );

    return NextResponse.json({
      ok: true,
      id: insertResult.rows[0]?.id ?? null,
      submittedAt: insertResult.rows[0]?.submitted_at ?? null,
    });
  } catch (error) {
    console.error("Failed to save registration submission:", error);
    return NextResponse.json(
      { error: "Failed to save registration data." },
      { status: 500 },
    );
  }
}
